spring:
  cloud:
    config:
      server: 
        git:
          uri: https://github.com/damontheimpulsive/ConfigData
          searchPaths: ConfigData
          
server:
  port: 8001
          
          
          

